# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70261c87150dc29783f3f0891a48752337d92c475e36094e022cec6482fa4873c8b846127b875cdeb264b2fc6c6de6e432d364405c30f9b947f6d538c4c17f87

test:
  secret_key_base: bb3d22c87ab2377633df0eeb99f44fa571cfc7ba157e1218d9441245dbcc66f44bee9abaef715d840abb2752498995c8fc6437d77d8448d46e9ceb97391826a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
